//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class flights
    {
        public flights()
        {
            this.flightsUsers = new HashSet<flightsUsers>();
        }
    
        public int idFlight { get; set; }
        public string citySource { get; set; }
        public string cityDestination { get; set; }
        public System.DateTime departureDateTime { get; set; }
        public string planeNumber { get; set; }
        public string pilotName { get; set; }
    
        public virtual cities cities { get; set; }
        public virtual ICollection<flightsUsers> flightsUsers { get; set; }
    }
}
